# 1. Import Basic Python Package

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pylab import rcParams

# 2. 了解問題：
(1) 定義問題：??(2) 蒐集資料

In [2]:
from sklearn.datasets import load_iris
iris_data = load_iris()
print(iris_data.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [3]:
print(iris_data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
# Features
print(iris_data.data)
print(iris_data.data.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
# Label
print(iris_data.target) 
print(iris_data.target.shape) 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150,)


# 2. Training and Testing Split
為了統一大家預測的結果請大家設定random_state=40,shuffle=True

In [0]:
from sklearn.model_selection import train_test_split
# split the data into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.33, random_state=40
                                                    , shuffle=True)

# 3. Classify Iris: Simple Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# 4. Prediction Result Evaluation

In [8]:
from sklearn import metrics
print('train evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_train, y_train_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_train, y_train_pred))
print('test evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_test, y_test_pred))

train evaluation---------------------------------
accuracy:0.97
confusion matirx:
 [[32  0  0]
 [ 0 33  2]
 [ 0  1 32]]
test evaluation---------------------------------
accuracy:1.00
confusion matirx:
 [[18  0  0]
 [ 0 15  0]
 [ 0  0 17]]


# 5. Logistic Regression Probability Output

In [9]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
y_test_pred = model.predict(X_test)
y_test_pred_proba = model.predict_proba(X_test)
print('Classification Output:\n', y_test_pred)
print('Probability Output:\n', y_test_pred_proba)

Classification Output:
 [0 1 2 2 1 2 1 1 1 0 1 0 0 2 1 2 2 2 1 1 2 2 1 0 1 0 0 2 0 1 1 0 0 0 0 2 0
 0 2 0 0 1 2 2 2 0 2 2 1 0]
Probability Output:
 [[9.79348737e-01 2.06511687e-02 9.40064741e-08]
 [1.23762207e-02 7.65824904e-01 2.21798876e-01]
 [1.47329002e-04 9.18996371e-02 9.07953034e-01]
 [4.92907072e-07 8.44515586e-03 9.91554351e-01]
 [2.73862709e-02 9.16405713e-01 5.62080166e-02]
 [3.99965080e-05 3.50763246e-02 9.64883679e-01]
 [3.09004795e-03 7.74678237e-01 2.22231715e-01]
 [2.03517186e-02 8.98292263e-01 8.13560185e-02]
 [1.42107003e-02 7.42885114e-01 2.42904186e-01]
 [9.68422995e-01 3.15769077e-02 9.70366829e-08]
 [1.29596012e-02 8.69502971e-01 1.17537428e-01]
 [9.65927598e-01 3.40721729e-02 2.28777216e-07]
 [9.79905147e-01 2.00947879e-02 6.49803022e-08]
 [1.91330591e-03 4.92979630e-01 5.05107064e-01]
 [7.86581375e-02 9.15385045e-01 5.95681710e-03]
 [1.49151673e-05 2.58534978e-02 9.74131587e-01]
 [1.11586856e-03 4.30600456e-01 5.68283675e-01]
 [4.17753307e-05 6.56588826e-02 9.34

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# 6. 調整C值

In [10]:
"""調整看看C看看預測結果"""
model = LogisticRegression(C=1)
model.fit(X_train,y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
print('train evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_train, y_train_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_train, y_train_pred))
print('test evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_test, y_test_pred))

train evaluation---------------------------------
accuracy:0.97
confusion matirx:
 [[32  0  0]
 [ 0 33  2]
 [ 0  1 32]]
test evaluation---------------------------------
accuracy:1.00
confusion matirx:
 [[18  0  0]
 [ 0 15  0]
 [ 0  0 17]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# 7. 調整multi_class
multinomial或ovr哪個performance好呢？
提示： defaul的solver='liblinear'並不支援multi_class='multinomial'，直接寫會報錯，因此記得加上solver='sag'。

In [11]:
"""調整muti_class"""
model = LogisticRegression(solver='sag', multi_class='multinomial')
model.fit(X_train,y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
print('train evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_train, y_train_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_train, y_train_pred))
print('test evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_test, y_test_pred))

train evaluation---------------------------------
accuracy:0.98
confusion matirx:
 [[32  0  0]
 [ 0 33  2]
 [ 0  0 33]]
test evaluation---------------------------------
accuracy:1.00
confusion matirx:
 [[18  0  0]
 [ 0 15  0]
 [ 0  0 17]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
